# Documentation links
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - portfolioKrimiIbrahim

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'  # Enable caching of npm modules directly in the setup-node action

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build 
          npm run test --if-present
          echo "Listing contents of the current directory:"
          ls -la
          echo "Listing contents of the build output directory (dist/):"
          ls -la dist/  # Ensure this directory is your actual output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98BD1AB5807C4DC1A212BB32235505C5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7519A6E03444DB6AF385261A8EAD104 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74ABA4A35CEC4E68ABD6DC21F90B61B8 }}
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portfolioKrimiIbrahim'
          slot-name: 'Production'
          package: './dist'  # Ensure this path matches the actual build output directory
