name: Build and deploy Node.js app to Azure Web App - portfolioKrimiIbrahim

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build 

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98BD1AB5807C4DC1A212BB32235505C5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7519A6E03444DB6AF385261A8EAD104 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74ABA4A35CEC4E68ABD6DC21F90B61B8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'portfolioKrimiIbrahim'
          slot-name: 'Production'
          package: .
